version: '3.8'

# Railway Docker Compose deployment
# Railway will use this file to deploy both backend and frontend services
# All credentials must be provided via Railway environment variables

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # Railway will set PORT automatically
    environment:
      # Database - Railway provides DATABASE_URL automatically for PostgreSQL service
      DATABASE_URL: ${DATABASE_URL}
      
      # Qdrant Vector DB
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      
      # OpenRouter LLM
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL_PRIMARY: ${OPENROUTER_MODEL_PRIMARY:-x-ai/grok-4.1-fast}
      OPENROUTER_MODEL_FALLBACK: ${OPENROUTER_MODEL_FALLBACK:-openai/gpt-oss-120b:free}
      OPENROUTER_TIMEOUT_PRIMARY: ${OPENROUTER_TIMEOUT_PRIMARY:-30}
      OPENROUTER_TIMEOUT_FALLBACK: ${OPENROUTER_TIMEOUT_FALLBACK:-60}
      
      # Embeddings
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-small}
      EMBEDDING_DIMENSION: ${EMBEDDING_DIMENSION:-1536}
      
      # Admin Panel Secrets
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY}
      ADMIN_SESSION_SECRET: ${ADMIN_SESSION_SECRET}
      
      # Application URLs
      APP_URL: ${APP_URL}
      BACKEND_URL: ${BACKEND_URL}
      
      # CORS - comma-separated list
      CORS_ORIGINS: ${CORS_ORIGINS}
      
      # Database fallback options
      SKIP_DB_INIT: ${SKIP_DB_INIT:-false}
      USE_IN_MEMORY_DB: ${USE_IN_MEMORY_DB:-false}
      
      # Port for Railway
      PORT: ${PORT:-8000}
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:${PORT:-8000}/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  admin-panel:
    build:
      context: .
      dockerfile: admin-panel/Dockerfile
    environment:
      # Next.js public environment variables (accessible in browser)
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
      # Railway sets PORT automatically - Next.js reads it from process.env.PORT
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:' + (process.env.PORT || '3000') + '/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend



