"""add_llm_models_and_global_settings

Revision ID: 6b1a79c454ff
Revises: 5e2390f2d75b
Create Date: 2025-12-13 16:37:17.945791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a79c454ff'
down_revision = '5e2390f2d75b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли таблица перед созданием
    from sqlalchemy import inspect, text
    from alembic import context
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Получаем список существующих таблиц
    existing_tables = inspector.get_table_names()
    
    if 'global_model_settings' not in existing_tables:
        op.create_table('global_model_settings',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('primary_model_id', sa.String(length=255), nullable=True),
            sa.Column('fallback_model_id', sa.String(length=255), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'llm_models' not in existing_tables:
        op.create_table('llm_models',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('model_id', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('is_custom', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('model_id')
        )
    
    # Проверяем, существует ли колонка llm_model в projects
    columns = [col['name'] for col in inspector.get_columns('projects')]
    if 'llm_model' not in columns:
        op.add_column('projects', sa.Column('llm_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'llm_model')
    op.drop_table('llm_models')
    op.drop_table('global_model_settings')
    # ### end Alembic commands ###


